-- Investment Portfolio & Transaction Analytics: schema
-- Money and quantities use NUMERIC (exact decimal), never FLOAT.
-- Identity columns are BY DEFAULT (not ALWAYS) so the loader can COPY explicit ids;
-- sequences are reset after the load.

CREATE TABLE customers (
    customer_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name    VARCHAR(100) NOT NULL,
    email        VARCHAR(150) UNIQUE NOT NULL,
    risk_profile VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_risk_profile CHECK (risk_profile IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE TABLE accounts (
    account_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT      NOT NULL,
    account_type VARCHAR(30) NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    opened_at    DATE        NOT NULL,
    CONSTRAINT fk_account_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT chk_account_type    CHECK (account_type IN ('BROKERAGE', 'RETIREMENT', 'CASH')),
    CONSTRAINT chk_account_status  CHECK (status IN ('ACTIVE', 'CLOSED'))
);

CREATE TABLE securities (
    security_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol        VARCHAR(20)  UNIQUE NOT NULL,
    security_name VARCHAR(150) NOT NULL,
    asset_type    VARCHAR(30)  NOT NULL,
    sector        VARCHAR(50),
    CONSTRAINT chk_asset_type CHECK (asset_type IN ('STOCK', 'ETF', 'BOND', 'MUTUAL_FUND'))
);

CREATE TABLE orders (
    order_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT        NOT NULL,
    security_id  BIGINT        NOT NULL,
    side         VARCHAR(10)   NOT NULL,
    quantity     NUMERIC(18,4) NOT NULL,
    order_type   VARCHAR(20)   NOT NULL,
    order_status VARCHAR(20)   NOT NULL,
    submitted_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_account  FOREIGN KEY (account_id)  REFERENCES accounts(account_id),
    CONSTRAINT fk_order_security FOREIGN KEY (security_id) REFERENCES securities(security_id),
    CONSTRAINT chk_order_side     CHECK (side IN ('BUY', 'SELL')),
    CONSTRAINT chk_order_type     CHECK (order_type IN ('MARKET', 'LIMIT')),
    CONSTRAINT chk_order_status   CHECK (order_status IN ('FILLED', 'CANCELLED', 'REJECTED')),
    CONSTRAINT chk_order_quantity CHECK (quantity > 0)
);

-- Cash ledger + trades. Trade fees live in `fees`; there is no FEE transaction type.
CREATE TABLE transactions (
    transaction_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       BIGINT        NOT NULL,
    security_id      BIGINT,
    transaction_type VARCHAR(30)   NOT NULL,
    quantity         NUMERIC(18,4),
    price            NUMERIC(18,4),
    amount           NUMERIC(20,4) NOT NULL,
    transaction_date TIMESTAMP     NOT NULL,
    CONSTRAINT fk_transaction_account  FOREIGN KEY (account_id)  REFERENCES accounts(account_id),
    CONSTRAINT fk_transaction_security FOREIGN KEY (security_id) REFERENCES securities(security_id),
    CONSTRAINT chk_transaction_type    CHECK (transaction_type IN ('BUY', 'SELL', 'DIVIDEND', 'DEPOSIT', 'WITHDRAWAL')),
    CONSTRAINT chk_transaction_amount  CHECK (amount >= 0),
    -- trades and dividends must reference a security; cash movements must not
    CONSTRAINT chk_transaction_security CHECK (
        (transaction_type IN ('BUY', 'SELL', 'DIVIDEND') AND security_id IS NOT NULL)
        OR (transaction_type IN ('DEPOSIT', 'WITHDRAWAL') AND security_id IS NULL)
    )
);

CREATE TABLE holdings (
    holding_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT        NOT NULL,
    security_id  BIGINT        NOT NULL,
    quantity     NUMERIC(18,4) NOT NULL,
    average_cost NUMERIC(18,4) NOT NULL,
    updated_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_holding_account  FOREIGN KEY (account_id)  REFERENCES accounts(account_id),
    CONSTRAINT fk_holding_security FOREIGN KEY (security_id) REFERENCES securities(security_id),
    CONSTRAINT uq_account_security UNIQUE (account_id, security_id),
    CONSTRAINT chk_holding_quantity CHECK (quantity >= 0)
);

CREATE TABLE market_prices (
    security_id BIGINT        NOT NULL REFERENCES securities(security_id),
    price_date  DATE          NOT NULL,
    open_price  NUMERIC(18,4) NOT NULL,
    high_price  NUMERIC(18,4) NOT NULL,
    low_price   NUMERIC(18,4) NOT NULL,
    close_price NUMERIC(18,4) NOT NULL,
    volume      BIGINT,
    PRIMARY KEY (security_id, price_date)
);

CREATE TABLE dividends (
    dividend_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id        BIGINT        NOT NULL REFERENCES securities(security_id),
    ex_date            DATE          NOT NULL,
    payment_date       DATE          NOT NULL,
    dividend_per_share NUMERIC(18,4) NOT NULL
);

CREATE TABLE fees (
    fee_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT        NOT NULL REFERENCES transactions(transaction_id),
    fee_type       VARCHAR(30)   NOT NULL,
    amount         NUMERIC(18,4) NOT NULL CHECK (amount >= 0)
);
